use_frameworks!

target 'PagedUITableViewController_Example' do
  pod 'PagedUITableViewController', :path => '../'

  target 'PagedUITableViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
